### ISSUE TITLE
fails to build with optparse-applicative 0.13.2.0

### ISSUE THREAD

**Issue by clinty** [fpco/hackage-mirror#5]
with optparse-applicative 0.13.2.0:

```
main/Main.hs:27:7: error:
    Module ‘Options.Applicative’ does not export ‘(<>)’
```

**Comment by snoyberg** [comment]
With the advent of Hackage Security, we don't actually use or maintain this repo anymore. What's your interest in using this?

**Comment by clinty** [comment]
It is my understanding that it's to facilitate [Software Heritage](https://www.softwareheritage.org/)

cc: @zacchiro @joeyh

**Comment by zacchiro** [comment]
yep, that's correct, thanks for the higlight @clinty .

In short, to guarantee archival of Cabal packages in Software Heritage, we need a way to:
1) list all currently available (source) packages in all their versions
2) retrieve those that we hadn't retrieve in the past and add it to the archive

(2) is easy, as they're just tarballs and we have existing loaders for that
(1) requires interpreting Cabal metadata, and we were thinking of building on top of hackage-mirror. Maybe there is a best way to do this now?

TIA

**Comment by snoyberg** [comment]
There's some documentation here:

https://github.com/haskell/hackage-security/

But I've honestly never looked at it myself. If I just wanted to determine the list of all packages, I'd look at the `.cabal` file names in the tarball, which have a format:

    packagename/version/packagename.cabal

Then you can parse all of the filenames, determine the packagename-version combos available, and download each of those from Hackage.

There's also the all-cabal-hashes repo (https://github.com/commercialhaskell/all-cabal-hashes/tree/hackage) which provides the same information as a Git repository. The JSON files in there may provide more useful information to you if you're interested, as it contains hashes, file sizes, and a download URL. For example:

https://github.com/commercialhaskell/all-cabal-hashes/blob/hackage/conduit/1.3.0.2/conduit.json

**Comment by zacchiro** [comment]
Thanks, that helps! It looks like that all-cabal-hashes would be perfect for us, as it allows to retrieve recent metadata without having to retrieve all the source code (in case we had already ingested most of it in the past).
Is "commerciahaskell" something that is officially maintained by the haskell community in some form, or is it a 3rd party thing?

**Comment by snoyberg** [comment]
It's a different group than maintains Hackage, but yes, it's officially
maintained by part of the community.
